# Generated by Django 2.2.11 on 2020-06-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tweets',
            new_name='Tweet',
        ),
    ]
