# Generated by Django 2.2.11 on 2020-06-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200606_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='Tweet',
        ),
        migrations.AddField(
            model_name='tweet',
            name='Date',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='State',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='TweetId',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='Sentiment',
            field=models.FloatField(),
        ),
    ]
