# Generated by Django 2.2.11 on 2020-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CARDdata',
            fields=[
                ('Data_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Confirmed', models.IntegerField()),
                ('Active', models.IntegerField()),
                ('Recovered', models.IntegerField()),
                ('Deceased', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DateAndArea',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='From',
            fields=[
                ('PatientId', models.IntegerField(primary_key=True, serialize=False)),
                ('DateAndAreaId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('CARDdataId', models.IntegerField(primary_key=True, serialize=False)),
                ('DateAndAreaId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('TweetId', models.IntegerField(primary_key=True, serialize=False)),
                ('DateAndAreaId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='State',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='State',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='TweetId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
