# Generated by Django 2.2.11 on 2020-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200718_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='TweetId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
