# Generated by Django 2.2.11 on 2020-07-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200718_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateandarea',
            name='Date',
            field=models.DateField(),
        ),
    ]
